apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
    - image: s218325308/task5.1p-app:1.1.2
      #imagePullPolicy: Never
      name: nodewebapp
      ports:
        - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
